services:
  k6:
    image: grafana/k6:${K6_IMAGE_TAG}
    user: "${UID}:${GID}"
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./${SCRIPT}:/scripts/script.js:ro
      - ./words_alpha.txt:/scripts/words_alpha.txt:ro
      - ./output:/output
    command: run /scripts/script.js
